
project_id = "xwjgchqoqfmjnwhfqqdb"
[api]
enabled_apis = ["rest", "graphql", "realtime"]
[api.cors]
allowed_headers = ["authorization", "x-client-info", "apikey", "content-type"]
[functions.getPlayerData]
verify_jwt = false
