
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwjgchqoqfmjnwhfqqdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3amdjaHFvcWZtam53aGZxcWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTY3MjcsImV4cCI6MjA1NjM5MjcyN30.oRuiiVTYhTHZDlA9Cc6gLQR43HjPWLwnjZra6LNLluo";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
